### ISSUE TITLE
Create a refresh function

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/ipt_connect#8]
Currently, pages refreshes only when someone wants to access them, and after a given minimum amount of time (otherwise the cache version is displayed). It is in practice a good thing, but when too many people try to access a cpu-costly page at the same time, the server receives too much requests and crashes.

We need to change this. We need a refresh function that can be called e.g. through the admin panel by pressing a button, and where every pages refresh. When participants access the web site, they only see the pages that are in the cache.

**Comment by xuod** [comment]
I added an update_points function that receives the post_save signal from Round : when a round is saved, eg from the admin panel, it triggers this function that computes points for participants and teams (which were added a field points_so_far). Then all views should use this db field. That's a progress, but it's not perfect yet (some views still need to compute some scores).

**Comment by mhrz** [comment]
@xuod Could you please explain your improvement of yesterday?

**Comment by xuod** [comment]
Some detail to the optimization : 
- `Round` model now does the computation of its scores (I call score the averaged grades of the jury for one round) and points (=scores * coefficients) in the function `update_scores`.
- `Team`, `Participant` and `Problem` models each have an `update_scores` function too that computes the total points and/or the mean scores in for each role (see #19 ) and save those to the database.
- in admin.py, I override the `save` and `save_related` functions, so that when a round is saved from the admin, it will : 
1. save the rejections and the jury grades in the database
2. call `Round.update_scores`
3. call `Team.update_scores` for the teams participating in the round
4. each of these call `Participant.update_scores` for its participants
5. call `Problem.update_scores`
